
import 'package:d_intern/services/product_service.dart';
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'data/hive_boxes.dart';
import 'models/product.dart';
import 'models/stock.dart';
import 'repositories/impl/product_hive_repo.dart';
import 'repositories/impl/stock_hive_repo.dart';
import 'services/stock_service.dart';
import 'usecases/product_usecase.dart';
import 'usecases/stock_usecase.dart';
import 'ui/pages/home_page.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();

  // register adapters (generated by build_runner)
  Hive.registerAdapter(ProductStatusAdapter());
  Hive.registerAdapter(ProductAdapter());
  Hive.registerAdapter(StockAdapter());

  // open boxes
  await Hive.openBox<Product>(Boxes.products);
  await Hive.openBox<Stock>(Boxes.stocks);
  await Hive.openBox(Boxes.settings);

  // repos
  final productRepo = ProductHiveRepo();
  final stockRepo = StockHiveRepo();

  await productRepo.init();
  await stockRepo.init();

  // services
  final productService = ProductService(productRepo);
  final stockService = StockService(stockRepo);

  // usecases
  final productUsecase = ProductUsecase(productService);
  final stockUsecase = StockUsecase(stockService);

  runApp(MyApp(productUsecase: productUsecase, stockUsecase: stockUsecase));
}

class MyApp extends StatelessWidget {
  final ProductUsecase productUsecase;
  final StockUsecase stockUsecase;

  const MyApp({required this.productUsecase, required this.stockUsecase, Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Warehouse Inventory',
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      home: HomePage(productUsecase: productUsecase, stockUsecase: stockUsecase),
    );
  }
}
